import { ReactNode } from "react";
import { MdCode, MdHome, MdTrendingUp } from "react-icons/md";
import {
  SiAlgolia,
  SiBun,
  SiDocker,
  SiExpo,
  SiFirebase,
  SiFlutter,
  SiHono,
  SiLaravel,
  SiMariadb,
  SiNestjs,
  SiNuxtdotjs,
  SiOpenjdk,
  SiPostgresql,
  SiReact,
  SiRedis,
  SiSocketdotio,
  SiSpringboot,
  SiSqlite,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiUnrealengine,
  SiVuedotjs,
  SiWebpack,
} from "react-icons/si";
import { TbWorld } from "react-icons/tb";

const iconMap: Record<string, ReactNode> = {
  Algolia: <SiAlgolia color="#5468FF" />,
  Bun: <SiBun color="#FBF0DF" />,
  Code: <MdCode color="#2ecc71" />,
  Docker: <SiDocker color="#2496ED" />,
  Expo: <SiExpo color="#000020" />,
  Firebase: <SiFirebase color="#DD2C00" />,
  Flutter: <SiFlutter color="#2FB8F6" />,
  Home: <MdHome color="#d35400" />,
  Hono: <SiHono color="#E36002" />,
  Java: <SiOpenjdk color="#f89820" />,
  Laravel: <SiLaravel color="#F05340" />,
  MariaDB: <SiMariadb color="#008bb2" />,
  Nest: <SiNestjs color="#E0234E" />,
  Nuxt: <SiNuxtdotjs color="#00DC82" />,
  Postgres: <SiPostgresql color="#4169E1" />,
  React: <SiReact color="#58C4DC" />,
  "React Native": <SiReact color="#61DAFB" />,
  Redis: <SiRedis color="#DC382D" />,
  "Socket.IO": <SiSocketdotio color="#010101" />,
  "Spring Boot": <SiSpringboot color="#6DB33F" />,
  SQLite: <SiSqlite color="#429CD5" />,
  Supabase: <SiSupabase color="#3CCE8D" />,
  Tailwind: <SiTailwindcss color="#38BDF8" />,
  TrendingUp: <MdTrendingUp color="#3498db" />,
  Typescript: <SiTypescript color="#3178C6" />,
  "Unreal Engine": <SiUnrealengine color="#000000" />,
  "Vue 3": <SiVuedotjs color="#4FC08D" />,
  Webpack: <SiWebpack color="#8DD6F9" />,
  World: <TbWorld color="#F1A20F" />,
};

export default iconMap;
